import PDFDocument from 'pdfkit';
import { OnePagerBlueprint } from './ai';

export async function generatePdf(blueprint: OnePagerBlueprint): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        try {
            // The "Design" part of the separation: hardcoded margins, fonts, colors
            const doc = new PDFDocument({
                margin: 50,
                size: 'A4',
                info: { Title: `${blueprint.project_name} - Executive Summary`, Author: 'Forma' }
            });

            const buffers: Buffer[] = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));
            doc.on('error', reject);

            // Header / Project Name
            doc.fontSize(24).font('Helvetica-Bold').fillColor('#0F172A')
               .text(blueprint.project_name.toUpperCase(), { align: 'center' });
            doc.moveDown(0.5);
            
            doc.fontSize(10).font('Helvetica').fillColor('#64748B')
               .text('CONFIDENTIAL INVESTMENT MEMORANDUM', { align: 'center', characterSpacing: 2 });
            doc.moveDown(2);

            // Helper to draw sections
            const addSection = (title: string, content: string) => {
                // Section Divider
                doc.moveTo(50, doc.y).lineTo(545, doc.y).lineWidth(0.5).strokeColor('#E2E8F0').stroke();
                doc.moveDown(1);
                
                // Title
                doc.fontSize(14).font('Helvetica-Bold').fillColor('#3B82F6')
                   .text(title.toUpperCase());
                doc.moveDown(0.5);
                
                // Content
                doc.fontSize(11).font('Helvetica').fillColor('#334155').lineGap(4)
                   .text(content, { align: 'justify' });
                doc.moveDown(1.5);
            };

            addSection('Executive Summary', blueprint.executive_summary);
            addSection('Problem Statement', blueprint.problem_statement);
            addSection('Proposed Solution', blueprint.solution);
            addSection('Market Opportunity', blueprint.market_opportunity);
            addSection('Token Utility', blueprint.token_utility);
            addSection('Team & Roadmap', blueprint.team_or_roadmap);

            // Footer
            const bottom = doc.page.height - 50;
            doc.fontSize(8).fillColor('#94A3B8').text('Generated by Forma AI', 50, bottom, { align: 'center' });

            doc.end();
        } catch (error: any) {
            console.error('[Engine] PDF Generation Error:', error.message);
            reject(new Error('PDF generation failed'));
        }
    });
}
